export enum PERMISSION {
	ADMIN_PANEL_TEACHERS_SHOW = 'adminPanel.teachers.show',
	ADMIN_PANEL_MAIN_SHOW = 'adminPanel.main.show',
	ADMIN_PANEL_COMMENTS_SHOW = 'adminPanel.comments.show',
	ADMIN_PANEL_DEPARTMENTS_SHOW = 'adminPanel.departments.show',
	ADMIN_PANEL_USERS_SHOW = 'adminPanel.users.show',
	ADMIN_PANEL_STUDENTS_SHOW = 'adminPanel.students.show',
	ADMIN_PANEL_GROUPS_SHOW = 'adminPanel.groups.show',
	ADMIN_PANEL_GRANTS_SHOW = 'adminPanel.grants.show',
	ADMIN_PANEL_CATHEDRAS_SHOW = 'adminPanel.cathedras.show',
	ADMIN_PANEL_DISCIPLINES_SHOW = 'adminPanel.disciplines.show',
	ADMIN_PANEL_QUESTIONS_SHOW = 'adminPanel.questions.show',
	ADMIN_PANEL_ROLES_SHOW = 'adminPanel.roles.show',
	ADMIN_PANEL_SUBJECTS_SHOW = 'adminPanel.subjects.show',

	ADMISSION_GET = 'admission.get',
	ADMISSION_DELETE = 'admission.delete',
	ADMISSION_PRIORITIES_GET = 'admission.priorities.get',
	ADMISSION_PRIORITIES_APPROVE = 'admission.priorities.approve',

	CATHEDRAS_CREATE = 'cathedras.create',
	CATHEDRAS_UPDATE = 'cathedras.update',
	CATHEDRAS_DELETE = 'cathedras.delete',

	DISCIPLINE_RESOURCES_CREATE = 'disciplineResources.create',
	DISCIPLINE_RESOURCES_UPDATE = 'disciplineResources.update',
	DISCIPLINE_RESOURCES_DELETE = 'disciplineResources.delete',

	DISCIPLINE_TEACHERS_CREATE = 'disciplineTeachers.create',
	DISCIPLINE_TEACHERS_UPDATE = 'disciplineTeachers.update',
	DISCIPLINE_TEACHERS_DELETE = 'disciplineTeachers.delete',
	DISCIPLINE_DELETE = 'discipline.delete',
	DISCIPLINE_UPDATE = 'discipline.update',

	ENTRANT_CONTRACT_CREATE = 'entrant.contract.create',

	GROUPS_CREATE = 'groups.create',
	GROUPS_UPDATE = 'groups.update',
	GROUPS_DELETE = 'groups.delete',
	GROUPS_$GROUPID_ADMIN_SWITCH = 'groups.$groupId.admin.switch',
	GROUPS_$GROUPID_ANSWERS_SEND = 'groups.$groupId.answers.send',
	GROUPS_$GROUPID_CAPTAIN_GET = 'groups.$groupId.captain.get',
	GROUPS_$GROUPID_DISCIPLINES_CREATE = 'groups.$groupId.disciplines.create',
	GROUPS_$GROUPID_DISCIPLINES_GET = 'groups.$groupId.disciplines.get',
	GROUPS_$GROUPID_SELECTIVE_GET = 'groups.$groupId.selective.get',
	GROUPS_$GROUPID_DISCIPLINES_TEACHERS_GET = 'groups.$groupId.disciplines.teachers.get',
	GROUPS_$GROUPID_DISCIPLINE_TEACHERS_REMOVE = 'groups.$groupId.disciplineTeachers.remove',
	GROUPS_$GROUPID_EVENTS_CREATE = 'groups.$groupId.events.create',
	GROUPS_$GROUPID_EVENTS_GET = 'groups.$groupId.events.get',
	GROUPS_$GROUPID_EVENTS_UPDATE = 'groups.$groupId.events.update',
	GROUPS_$GROUPID_EVENTS_DELETE = 'groups.$groupId.events.delete',
	GROUPS_$GROUPID_QUESTIONS_GET = 'groups.$groupId.questions.get',
	GROUPS_$GROUPID_STUDENTS_ADD = 'groups.$groupId.students.add',
	GROUPS_$GROUPID_STUDENTS_GET = 'groups.$groupId.students.get',
	GROUPS_$GROUPID_STUDENTS_REMOVE = 'groups.$groupId.students.remove',
	GROUPS_$GROUPID_STUDENTS_VERIFY = 'groups.$groupId.students.verify',
	GROUPS_$GROUPID_STUDENTS_UNVERIFIED_GET = 'groups.$groupId.students.unverified.get',
	GROUPS_$GROUPID_TRANSFER = 'groups.$groupId.transfer',
	GROUPS_CAPTAIN_SWITCH = 'groups.captain.switch',
	GROUPS_$GROUPID_LIST_GET = 'groups.$groupId.list.get',
	GROUPS_$GROUPID_LEAVE = 'groups.$groupId.leave',

	QUESTIONS_CREATE = 'questions.create',
	QUESTIONS_UPDATE = 'questions.update',
	QUESTIONS_DELETE = 'questions.delete',
	QUESTIONS_ROLES_GIVE = 'questions.roles.give',
	QUESTIONS_ROLES_DELETE = 'questions.roles.delete',

	RESOURCES_CREATE = 'resources.create',
	RESOURCES_UPDATE = 'resources.update',
	RESOURCES_DELETE = 'resources.delete',

	ROLES_CREATE = 'roles.create',
	ROLES_$ROLEID_UPDATE = 'roles.update',
	ROLES_$ROLEID_DELETE = 'roles.delete',
	ROLES_$ROLEID_GRANTS_CREATE = 'roles.$roleId.grants.create',
	ROLES_$ROLEID_GRANT_CREATE = 'roles.$roleId.grant.create',
	ROLES_$ROLEID_GRANTS_UPDATE = 'roles.$roleId.grants.update',
	ROLES_$ROLEID_GRANTS_DELETE = 'roles.$roleId.grants.delete',

	COMMENTS_GET = 'comments.get',
	COMMENTS_UPDATE = 'comments.update',
	COMMENTS_DELETE = 'comments.delete',

	SCHEDULE_PARSE = 'schedule.parse',

	STUDENTS_$STUDENTID_DELETE = 'students.$studentId.delete',
	STUDENTS_GET = 'students.get',
	STUDENTS_$STUDENTID_UPDATE = 'students.$studentId.update',
	STUDENTS_CREATE = 'students.create',
	STUDENTS_$STUDENTID_GET = 'students.$studentId.get',
	STUDENTS_$STUDENTID_SELECTIVE_GET = 'students.$studentId.selective.get',

	SUBJECTS_CREATE = 'subjects.create',
	SUBJECTS_UPDATE = 'subjects.update',
	SUBJECTS_DELETE = 'subjects.delete',

	USERS_CREATE = 'users.create',
	USERS_GET = 'users.get',
	USERS_UPDATE = 'users.update',
	USERS_DELETE = 'users.delete',
	USERS_GROUPS_SWITCH = 'users.groups.switch',
	USERS_$USERID_GET = 'users.$userId.get',
	USERS_$USERID_UPDATE = 'users.$userId.update',
	USERS_$USERID_DELETE = 'users.$userId.delete',
	USERS_$USERID_CONTACTS_CREATE = 'users.$userId.contacts.create',
	USERS_$USERID_CONTACTS_UPDATE = 'users.$userId.contacts.update',
	USERS_$USERID_CONTACTS_GET = 'users.$userId.contacts.get',
	USERS_$USERID_CONTACTS_DELETE = 'users.$userId.contacts.delete',
	USERS_$USERID_GROUP_REQUEST = 'users.$userId.group.request',
	USERS_$USERID_POLL_TEACHERS_GET = 'users.$userId.poll.teachers.get',
	USERS_$USERID_SELECTIVE_GET = 'users.$userId.selective.get',
	USERS_$USERID_SELECTIVE_DISCIPLINES = 'users.$userId.selectiveDisciplines',
	USERS_$USERID_SUPERHERO_CREATE = 'users.$userId.superhero.create',
	USERS_$USERID_STUDENT_UPDATE = 'users.$userId.student.update',
	USERS_$USERID_TELEGRAM_LINK = 'users.$userId.telegram.link',
	USERS_$USERID_TEACHERS_$TEACHERID_DISCIPLINES_GET = 'users.$userId.teachers.$teacherId.disciplines.get',

	TEACHERS_CREATE = 'teachers.create',
	TEACHERS_$TEACHERID_UPDATE = 'teachers.$teacherId.update',
	TEACHERS_$TEACHERID_DELETE = 'teachers.$teacherId.delete',
	TEACHERS_$TEACHERID_CATHEDRAS_UPDATE = 'teachers.$teacherId.cathedras.update',
	TEACHERS_$TEACHERID_CATHEDRAS_DELETE = 'teachers.$teacherId.cathedras.delete',
	TEACHERS_$TEACHERID_CONTACTS_CREATE = 'teachers.$teacherId.contacts.create',
	TEACHERS_$TEACHERID_CONTACTS_UPDATE = 'teachers.$teacherId.contacts.update',
	TEACHERS_$TEACHERID_CONTACTS_DELETE = 'teachers.$teacherId.contacts.delete',

	PAGE_TEXTS_CREATE = 'pages.create',
	PAGE_TEXTS_UPDATE = 'pages.update',
}
