import { PERMISSION } from '@fictadvisor/utils/security';

export const adminPermissions: Record<string, PERMISSION> = {
  roles: PERMISSION.ADMIN_PANEL_ROLES_SHOW,
  users: PERMISSION.ADMIN_PANEL_USERS_SHOW,
  students: PERMISSION.ADMIN_PANEL_STUDENTS_SHOW,
  groups: PERMISSION.ADMIN_PANEL_GROUPS_SHOW,
  departments: PERMISSION.ADMIN_PANEL_DEPARTMENTS_SHOW,
  teachers: PERMISSION.ADMIN_PANEL_TEACHERS_SHOW,
  disciplines: PERMISSION.ADMIN_PANEL_DISCIPLINES_SHOW,
  subjects: PERMISSION.ADMIN_PANEL_SUBJECTS_SHOW,
  questions: PERMISSION.ADMIN_PANEL_QUESTIONS_SHOW,
  comments: PERMISSION.ADMIN_PANEL_COMMENTS_SHOW,
  grants: PERMISSION.ADMIN_PANEL_GRANTS_SHOW,
  admin: PERMISSION.ADMIN_PANEL_MAIN_SHOW,
};
