import {
  IconButtonColor,
  IconButtonSize,
  IconType,
  SortButtonOrder,
} from '@/components/common/ui/icon-button/IconButton';
import {
  SortButton,
  TrashBucketButton,
} from '@/components/common/ui/icon-button/variants';

import styles from '../test-pages.module.scss';

const IconButtonsPage = () => (
  <div className={styles['test-page-wrap']}>
    <div className={styles['test-page-content']}>
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.ERROR}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.LARGE}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.ASCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
        disabled={true}
      />
      <SortButton
        size={IconButtonSize.NORMAL}
        order={SortButtonOrder.DESCENDING}
        color={IconButtonColor.PRIMARY}
        shape={IconType.SQUARE}
        disabled={true}
      />

      <TrashBucketButton
        size={IconButtonSize.LARGE}
        shape={IconType.CIRCLE}
        color={IconButtonColor.SECONDARY}
      />
      <TrashBucketButton
        size={IconButtonSize.NORMAL}
        shape={IconType.CIRCLE}
        color={IconButtonColor.SECONDARY}
      />
      <TrashBucketButton
        size={IconButtonSize.LARGE}
        shape={IconType.CIRCLE}
        disabled={true}
        color={IconButtonColor.SECONDARY}
      />
      <TrashBucketButton
        size={IconButtonSize.NORMAL}
        shape={IconType.CIRCLE}
        disabled={true}
        color={IconButtonColor.SECONDARY}
      />
    </div>
  </div>
);

export default IconButtonsPage;
