name: 'Install Node and dependencies'

description: 'Set up Node and dependencies'
runs:
  using: composite
  steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Cache Yarn
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install yarn
      shell: bash
      run: |
        corepack enable
        yarn set version stable
    - name: Install dependencies
      shell: bash
      run: yarn workspaces focus --all
    - name: Generate Prisma
      shell: bash
      run: npx prisma generate --schema ./fictadvisor-api/prisma/schema.prisma