import { URLSearchParams } from 'node:url';

const SEMESTER = 2;

export const VIEW_SCHEDULE_PARAMS = new URLSearchParams({
  __EVENTVALIDATION:
    '/wEdAAEAAAD/////AQAAAAAAAAAPAQAAAAYAAAAIsA3rWl3AM+6E94I5ke7WZqDu1maj7tZmCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANqZqakPTbOP2+koNozn1gOvqUEW',
  __EVENTTARGET: '',
  ctl00$MainContent$ddlSemesterType: SEMESTER.toString(),
});

export const WEEK_TAGS = {
  0: 'ctl00_MainContent_FirstScheduleTable',
  1: 'ctl00_MainContent_SecondScheduleTable',
};

export const GROUP_SELECTION_URL = 'http://epi.kpi.ua/Schedules/ScheduleGroupSelection.aspx/GetGroups';
export const GROUP_CODE_REGEX = /І[МПКАСОВТ]-([зпв]|зп)?\d\d(мн|мп|ф)?і?/;
export const VIEW_SCHEDULE_URL_BASE = 'http://epi.kpi.ua/Schedules/ViewSchedule.aspx?g=';
export const SCHEDULE_GROUP_SELECTION_URL = 'http://epi.kpi.ua/Schedules/ScheduleGroupSelection.aspx';

export const EVENTVALIDATION = '/wEdAAEAAAD/////AQAAAAAAAAAPAQAAAAUAAAAIsA3rWl3AM+6E94I5Tu9cRJoVjv0LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHfLZVQO6kVoZVPGurJN4JJIAuaU';

export const SCHEDULE_SELECTION_FORM_SELECTOR = 'form[name=\'aspnetForm\']';
export const DOMAIN_EXTRACTION_REGEX = /^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:/\n?]+)/igm;
export const GOOGLE_MAPS_URL = 'http://maps.google.com';