export enum Position {
  ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
  DEPARTMENT_CHAIR = 'DEPARTMENT_CHAIR',
  PROFESSOR = 'PROFESSOR',
  RESEARCH_ASSISTANT = 'RESEARCH_ASSISTANT',
  SENIOR_RESEARCH_ASSISTANT = 'SENIOR_RESEARCH_ASSISTANT',
  SENIOR_LECTURER = 'SENIOR_LECTURER',
  ASSISTANT = 'ASSISTANT',
  LEADING_RESEARCHER = 'LEADING_RESEARCHER',
  LECTURER = 'LECTURER',
}