name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-20.04
    steps:
      # Setup the environment
      - name: Environment setup
        id: env
        run: |
          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"
          
      # Build the application
      - uses: actions/checkout@v2
      - name: Docker image build
        run: |
          docker build -t "${{ steps.env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
