name: Deployment - Development

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Setup the environment
      - name: Environment setup
        id: env
        run: |
          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
      # Deploy the application on the virtual machine
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_DO_HOST }}
          username: ${{ secrets.PRODUCTION_DO_USERNAME }}
          password: ${{ secrets.PRODUCTION_DO_PASSWORD }}
          port: ${{ secrets.PRODUCTION_DO_PORT }}
          script: |
            cd ~/deployment/development/builds
            ./${{ steps.env.outputs.IMAGE_NAME }}.sh
      # Deploy the application on the virtual machine
      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_DO_HOST }}
          username: ${{ secrets.PRODUCTION_DO_USERNAME }}
          password: ${{ secrets.PRODUCTION_DO_PASSWORD }}
          port: ${{ secrets.PRODUCTION_DO_PORT }}
          script: |
            cd ~/deployment/development/runners
            ./${{ steps.env.outputs.IMAGE_NAME }}.sh